apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: proxysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  #storageClassName: local-storage
